repos:
- repo: local
  hooks:
  - id: pgindent
    name: pgindent
    entry: pgindent
    stages: [pre-commit]
    pass_filenames: true
    language: system
    files: \.c|\.h
- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
  - id: black
- repo: https://github.com/crate-ci/typos
  rev: v1.38.1
  hooks:
    - id: typos

